# -*- coding: utf-8 -*-
import io
p='flutter/lib/common/widgets/chat_page.dart'
lines=io.open(p,encoding='utf-8').read().split('\n')

# Insert helper methods just before the screenshot-options comment (i.e. after _openAiModelConfig block ends).
# We find the screenshot options comment block start
anchor=None
for i,l in enumerate(lines):
    if l.startswith('  /// 剪刀右侧下拉箭头'):
        anchor=i; break
assert anchor
# The methods to insert (they precede the screenshot dropdown block)
new= [
'  /// 切换“更多”弹出菜单（图标 + 文字说明）。',
'  void _toggleMoreMenu() {',
'    setState(() {',
'      _showMoreMenu = !_showMoreMenu;',
'      _showEmojiPicker = false;',
'      _atOverlayVisible = false;',
'    });',
'    if (_showMoreMenu) {',
'      chatModel.inputNode.unfocus();',
'    } else {',
'      chatModel.inputNode.requestFocus();',
'    }',
'  }',
'',
'  /// “更多”按钮下方的弹出面板：功能图标 + 文字说明。',
'  Widget _buildMorePanel() {',
'    final items = _moreMenuItems();',
'    if (items.isEmpty) return const SizedBox.shrink();',
'    final surface = dark ? const Color(0xFF2B2D32) : Colors.white;',
'    final border = dark ? const Color(0xFF3A3D43) : const Color(0xFFE5E5E5);',
'    final labelColor = dark ? const Color(0xFFB8BBC2) : const Color(0xFF555555);',
'    final textColor = dark ? const Color(0xFF999CA2) : const Color(0xFF777777);',
'    return Container(',
'      margin: const EdgeInsets.fromLTRB(8, 0, 8, 4),',
'      padding: const EdgeInsets.fromLTRB(14, 12, 14, 12),',
'      decoration: BoxDecoration(',
'        color: surface,',
'        borderRadius: BorderRadius.circular(12),',
'        border: Border.all(color: border, width: 0.5),',
'        boxShadow: [',
'          BoxShadow(',
'            color: Colors.black.withOpacity(dark ? 0.35 : 0.08),',
'            blurRadius: 10,',
'            offset: const Offset(0, 3),',
'          ),',
'        ],',
'      ),',
'      child: Wrap(',
'        spacing: 18,',
'        runSpacing: 12,',
'        children: <Widget>[',
'          for (final it in items)',
'            _moreMenuTile(it.$1, it.$2, it.$3, labelColor, textColor),',
'        ],',
'      ),',
'    );',
'  }',
'',
'  Widget _moreMenuTile(IconData icon, String label, VoidCallback onTap,',
'      Color iconColor, Color textColor) {',
'    return InkWell(',
'      borderRadius: BorderRadius.circular(10),',
'      onTap: onTap,',
'      child: SizedBox(',
'        width: 64,',
'        child: Column(',
'          mainAxisSize: MainAxisSize.min,',
'          children: <Widget>[',
'            Container(',
'              width: 46,',
'              height: 46,',
'              decoration: BoxDecoration(',
'                color: dark',
'                    ? const Color(0xFF25272C)',
'                    : const Color(0xFFF5F6F7),',
'                borderRadius: BorderRadius.circular(12),',
'              ),',
'              child: Icon(icon, size: 24, color: iconColor),',
'            ),',
'            const SizedBox(height: 6),',
'            Text(',
'              label,',
'              maxLines: 1,',
'              overflow: TextOverflow.ellipsis,',
'              style: TextStyle(fontSize: 11, color: textColor),',
'            ),',
'          ],',
'        ),',
'      ),',
'    );',
'  }',
'',
]
lines[anchor:anchor]=new
io.open(p,'w',encoding='utf-8').write('\n'.join(lines))
print('helpers inserted before', anchor+1)
