password = []
size = [
    0,
    0,
    0,
    0,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'adaptive'
scroll_style = 'scrollauto'
edge_scroll_edge_thickness = 100
image_quality = 'balanced'
custom_image_quality = [50]
show_remote_cursor = false
lock_after_session_end = false
terminal-persistent = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 0
disable_audio = false
disable_clipboard = false
enable-file-copy-paste = true
show_quality_monitor = false
follow_remote_cursor = false
follow_remote_window = false
keyboard_mode = 'legacy'
view_only = false
show_my_cursor = false
sync-init-clipboard = false
trackpad-speed = 100

[options]
zoom-cursor = ''
i444 = ''
collapse_toolbar = ''
custom-fps = '30'
codec-preference = 'auto'
swap-left-right-mouse = ''

[ui_flutter]

[info]
username = 'android'
hostname = 'OPPO-PFUM10'
platform = 'Android'
display_name = 'OPPO-PFUM10'
avatar = ''

[transfer]
write_jobs = []
read_jobs = []
