// LUODA 3.1.24 - AI meeting minutes service.
//
// Turns a meeting group's chat history into structured meeting minutes:
//   1. Load text messages from the meeting conversation.
//   2. Build a compact transcript.
//   3. Ask the active AI text profile to summarise into structured minutes.
//      Falls back to a local rule-based digest when no AI profile is
//      configured or the call fails, so the feature always works offline.

import 'dart:convert';

import 'package:flutter/foundation.dart';

import '../common/direct_chat.dart';
import '../common/direct_chat_sqlite.dart';
import 'ai_config_model.dart';
import 'platform_model.dart';

/// One saved minutes entry for a meeting.
class MeetingMinutesEntry {
  MeetingMinutesEntry({
    required this.meetingId,
    required this.title,
    required this.generatedAt,
    required this.body,
    required this.source,
    this.messageCount = 0,
  });

  final String meetingId;
  final String title;
  final DateTime generatedAt;
  final String body;

  /// 'ai' when generated by the LLM, 'local' for the rule-based fallback.
  final String source;
  final int messageCount;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'meeting_id': meetingId,
        'title': title,
        'generated_at': generatedAt.toUtc().toIso8601String(),
        'body': body,
        'source': source,
        'message_count': messageCount,
      };

  factory MeetingMinutesEntry.fromJson(Map<String, dynamic> json) =>
      MeetingMinutesEntry(
        meetingId: (json['meeting_id'] ?? '').toString(),
        title: (json['title'] ?? '').toString(),
        generatedAt:
            DateTime.tryParse((json['generated_at'] ?? '').toString()) ??
                DateTime.now(),
        body: (json['body'] ?? '').toString(),
        source: (json['source'] ?? 'local').toString(),
        messageCount: int.tryParse('${json['message_count'] ?? 0}') ?? 0,
      );
}

/// Builds a plain-text transcript from chat records (text kept verbatim,
/// file/image/voice reduced to short markers so the digest stays readable).
class MeetingTranscriptBuilder {
  static const int maxTranscriptChars = 6000;

  /// Sort newest-first history into chronological order.
  static List<DirectChatRecord> normalizeOrder(List<DirectChatRecord> records) {
    final sorted = List<DirectChatRecord>.from(records)
      ..sort((a, b) => a.sentAt.compareTo(b.sentAt));
    return sorted;
  }

  static String build(List<DirectChatRecord> records) {
    final sorted = normalizeOrder(records);
    final lines = <String>[];
    for (final r in sorted) {
      final who = _speaker(r);
      if (r.kind == DirectChatKind.text) {
        final t = r.text.trim();
        if (t.isEmpty) continue;
        lines.add('[$who] $t');
      } else if (r.kind == DirectChatKind.image) {
        lines.add('[$who] 发送了图片');
      } else if (r.kind == DirectChatKind.file) {
        lines.add('[$who] 发送了文件:' + (r.fileName.isNotEmpty ? r.fileName : '文件'));
      } else if (r.kind == DirectChatKind.voice) {
        lines.add('[$who] 发送了语音消息');
      }
    }
    var transcript = lines.join('\n');
    if (transcript.length > maxTranscriptChars) {
      transcript = transcript.substring(0, maxTranscriptChars);
    }
    return transcript;
  }

  static String _speaker(DirectChatRecord r) {
    final name = r.senderName.trim();
    if (name.isEmpty) return r.senderId;
    if (name == 'ОТ' || name == '我') return '我';
    return name;
  }
}

/// Local rule-based digest (offline fallback when AI is unavailable).
class LocalMinutesDigest {
  static String build(String meetingTitle, List<DirectChatRecord> records) {
    final sorted = MeetingTranscriptBuilder.normalizeOrder(records);
    final speakers = <String>{};
    var textCount = 0, fileCount = 0, imageCount = 0, voiceCount = 0;
    final topics = <String>[];
    const topicKeywords = <String>[
      '进度', '方案', '预算', '排期', '上线', '版本', '需求', '问题',
      '客户', '设计', '测试', '发布', '分工', '截止', '目标', '风险',
      '复盘', '计划',
    ];
    for (final r in sorted) {
      final who = MeetingTranscriptBuilder._speaker(r);
      speakers.add(who);
      switch (r.kind) {
        case DirectChatKind.text:
          textCount++;
          for (final k in topicKeywords) {
            if (r.text.contains(k)) { topics.add(k); break; }
          }
        case DirectChatKind.file:
          fileCount++;
        case DirectChatKind.image:
          imageCount++;
        case DirectChatKind.voice:
          voiceCount++;
        default:
          break;
      }
    }
    final buf = StringBuffer()
      ..writeln('📋 会议纪要(本地整理)')
      ..writeln('会议:$meetingTitle')
      ..writeln('参与人:' + (speakers.isEmpty ? '—' : speakers.join('、')))
      ..writeln('消息统计:文字 $textCount 条,文件 $fileCount,图片 $imageCount,语音 $voiceCount')
      ..writeln();
    if (topics.isNotEmpty) {
      buf.writeln('讨论主题(按关键词):' + topics.join('、'));
    } else {
      buf.writeln('讨论主题:暂无文字讨论记录');
    }
    buf.writeln();
    buf.writeln('提示:配置 AI 服务后可生成带议题、结论和待办的结构化纪要。');
    return buf.toString();
  }
}

/// High-level service: generate + persist meeting minutes.
class MeetingMinutesService {
  MeetingMinutesService._();
  static final MeetingMinutesService instance = MeetingMinutesService._();

  /// Test/UI hook: override the AI summariser. Defaults to [_askAi].
  /// Returning null makes [generate] fall back to the local digest.
  Future<String?> Function(String title, String transcript)? aiCaller;

  /// Test hook: override KV persistence so unit tests never touch FFI.
  static String Function(String key)? kvGetOverride;
  static Future<void> Function(String key, String value)? kvSetOverride;

  static const _storageKey = 'luoda_meeting_minutes_v1';

  List<MeetingMinutesEntry> _entries = [];

  List<MeetingMinutesEntry> get entries => List.unmodifiable(_entries);

  List<MeetingMinutesEntry> forMeeting(String meetingId) {
    final list = _entries.where((e) => e.meetingId == meetingId).toList()
      ..sort((a, b) => b.generatedAt.compareTo(a.generatedAt));
    return list;
  }

  void load() {
    try {
      final raw = kvGetOverride != null
          ? kvGetOverride!(_storageKey)
          : bind.mainGetLocalOption(key: _storageKey);
      if (raw.isEmpty) return;
      final list = jsonDecode(raw) as List;
      _entries = list
          .whereType<Map>()
          .map((e) => MeetingMinutesEntry.fromJson(Map<String, dynamic>.from(e)))
          .toList();
    } catch (e) {
      debugPrint('MeetingMinutes load failed: $e');
      _entries = [];
    }
  }

  Future<void> save() async {
    final json = jsonEncode(_entries.map((e) => e.toJson()).toList());
    if (kvSetOverride != null) {
      await kvSetOverride!(_storageKey, json);
    } else {
      await bind.mainSetLocalOption(key: _storageKey, value: json);
    }
  }

  Future<List<DirectChatRecord>> _loadConversation(String conversationId) async {
    final rows = await DirectChatSqlite.instance.forConversation(conversationId);
    return MeetingTranscriptBuilder.normalizeOrder(rows);
  }

  /// Generate minutes for a meeting group.
  Future<MeetingMinutesEntry> generate({
    required String meetingId,
    required String title,
    required String conversationId,
    bool persist = true,
  }) async {
    final records = await _loadConversation(conversationId);
    final transcript = MeetingTranscriptBuilder.build(records);
    var body = '';
    var source = 'local';
    if (transcript.trim().isNotEmpty) {
      final caller = aiCaller ?? _askAi;
      final aiBody = await caller(title, transcript);
      if (aiBody != null && aiBody.isNotEmpty) {
        body = aiBody;
        source = 'ai';
      }
    }
    if (body.isEmpty) {
      body = LocalMinutesDigest.build(title, records);
    }
    final entry = MeetingMinutesEntry(
      meetingId: meetingId,
      title: title,
      generatedAt: DateTime.now(),
      body: body,
      source: source,
      messageCount: records.length,
    );
    if (persist) {
      _entries.insert(0, entry);
      while (_entries.length > 50) { _entries.removeLast(); }
      await save();
    }
    return entry;
  }

  Future<String?> _askAi(String title, String transcript) async {
    final profile = AiConfig.current.getProfileByType(AiProfileType.text);
    if (!profile.enabled || profile.endpoint.isEmpty) return null;
    final prompt = '你是会议纪要助手。根据会议《$title》的讨论记录整理成结构化纪要,'
        '使用简体中文。要求:以 Markdown 输出,包含 ## 议题、## 讨论要点、'
        '## 结论、## 待办事项;待办事项若原文明确到人则写成 "- 待办:负责人 | 事项";'
        '只依据记录内容不要编造;记录过少时如实说明。\n\n讨论记录:\n---\n$transcript\n---';
    try {
      return await callAiText(profile, prompt, temperature: 0.3);
    } catch (e) {
      debugPrint('MeetingMinutes AI failed: $e');
      return null;
    }
  }
}
